export const Environments = {
  PORT: 'PORT',
  MODE: 'MODE',
  POSTGRES_HOST: 'POSTGRES_HOST',
  POSTGRES_PORT: 'POSTGRES_PORT',
  POSTGRES_USER: 'POSTGRES_USER',
  POSTGRES_PASSWORD: 'POSTGRES_PASSWORD',
  POSTGRES_DATABASE: 'POSTGRES_DATABASE',
  POSTGRES_RUN_MIGRATIONS: 'POSTGRES_RUN_MIGRATIONS',
  POSTGRES_SYNCHRONIZE: 'POSTGRES_SYNCHRONIZE',
  POSTGRES_LOGGING: 'POSTGRES_LOGGING',
};
